# This workflow updates image paths in Markdown files to GitHub URLs

name: Update Image Paths

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "convert-image-path"
  convert-image-path:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Updates image paths in Markdown files
      - name: Update image paths in Markdown
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status

          for file in */*/*.md; do

            # Update image paths
            if sed -i.bak -E "s|(\!\[.*\]\()\./images/(.*\))|\1https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$(dirname "$file")/images/\2|g" "$file"; then
                echo "Processing \"$file\""
                echo "Directory: $(dirname \"$file\")"
                echo "Updated image paths in \"$file\""
            else
                echo "No image paths found in \"$file\""
            fi

            # 이미지 경로를 변경
            if ! git diff --quiet "$file"; then
                git add "$file"
                echo "Added: \"$file\""
            else
                echo "No changes detected in \"$file\""
            fi
            echo "------------------------------------------------------------------------------------------"
          done

      # Commits changes if there are any
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          if git commit -m "Update image paths to GitHub URLs"; then
              echo "Changes committed successfully."
              git push
          else
              echo "No changes to commit."
          fi