# This workflow updates image paths in Markdown files to GitHub URLs

name: Update Image Paths

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "convert-image-path"
  convert-image-path:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Updates image paths in Markdown files
      - name: Update image paths in Markdown
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          
          image_path_pattern='\!\[.*\]\.\/images\/'

          for file in */*/*.md; do
            echo "------------------------------------------------------------------------------------------"
          
            # Create the name for the changed file
            temp_file="${file%.md}_image_path_changed.md"
          
            # Check if the corresponding changed file already exists
            if [ -f "$temp_file" ]; then
                echo "File \"$temp_file\" already exists. Skip!"
                continue
            fi
          
            # Check if the file contains image paths that need to be updated
            echo "Checking file: \"$file\" for image paths matching: '$image_path_pattern'"
            if grep -q "$image_path_pattern" "$file"; then
                # Create a backup of the original file
                cp "$file" "$temp_file"
          
                # Update image paths
                sed -i -E "s|(\!\[.*\]\()\./images/(.*\))|\1https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$(dirname "$file")/images/\2|g" "$temp_file"
          
                echo "Processing \"$temp_file\""
                echo "Directory: $(dirname \"$temp_file\")"
                echo "Updated image paths in \"$temp_file\""
          
                # Add
                git add "$temp_file"
                echo "Added: \"$temp_file\""
                
            else
                echo "No image paths found in \"$file\""
            fi
          done



      # Commits changes if there are any
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          if git commit -m "Update image paths to GitHub URLs"; then
              echo "Changes committed successfully."
              git push
          else
              echo "No changes to commit."
          fi